### ISSUE TITLE
MacOS development

### ISSUE THREAD

**Issue by TraceTheDog** [tryphotino/tryphotino.github.io#4]
Is there a system requirement as to which version of OSX is used for development?  I'm using Visual Studio 2019 running on 10.13 and 

Dyld Error Message:
  Symbol not found: _objc_opt_new
  Referenced from: /Users/USER/*/Photino.Native.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

**Comment by MikeYeager** [comment]
We honestly have not tried developing with older versions of the Mac OS, so we're in uncharted territory here. Our best guess is that it requires you upgrade to at least 10.15 (Catalina-2019). Our build pipeline is in Azure DevOps which no longer supports 10.13 (High Sierra-2017). It does support 10.14 (Mojave-2018). We could try building with that until it's no longer supported by the build pipeline, but it would still require you to upgrade.
