### ISSUE TITLE
Can not run demo apps on Windows 10

### ISSUE THREAD

**Issue by pahosler** [tryphotino/tryphotino.github.io#5]
Using template in VS and photinoapp in WSL2

When I try to run the app from Visual Studio I get
on line 26  in Program.cs
`window.NavigateToLocalFile("wwwroot/index.html");`

`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

from WSL2 line 12 in Program.cs
`var window = new PhotinoNET.PhotinoNET("My great app", options =>`

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'Photino.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libPhotino.Native: cannot open shared object file: No such file or directory
   at PhotinoNET.PhotinoNET.Photino_ctor(String title, IntPtr parentPhotinoNET, OnWebMessageReceivedCallback webMessageReceivedCallback, Boolean fullscreen, Int32 x, Int32 y, Int32 width, Int32 height)
   at PhotinoNET.PhotinoNET..ctor(String title, Action`1 configure, Boolean fullscreen, Int32 x, Int32 y, Int32 width, Int32 height)
   at HelloWorldApp.Program.Main(String[] args) in /mnt/g/workspace/Csharp/PhotinoApp/Program.cs:line 12
```

When I run the app on a full Linux desktop, I get no errors and the app runs as expected.

I'm not sure what's wrong or how to fix it...

**Comment by MikeYeager** [comment]
It's very likely that the VebView2 control is not installed. The next version (to be posted in the next day or so) will install it if it's not found. Please try installing it from this link: [](https://go.microsoft.com/fwlink/p/?LinkId=2124703) It installs only once for each machine and is evergreen, so it's always up to date. There will also be new samples coming soon with some minor breaking changes, but more functionality. Our plan is to have everything up to date for the release on Wednesday and no more breaking changes.

**Comment by whatevergeek** [comment]
hi, can you share which link to install it from?
I tried installing from nuget, but it didn't work:
dotnet add package Microsoft.Web.WebView2 --version 1.0.774.44

**Comment by whatevergeek** [comment]
> hi, can you share which link to install it from?
> I tried installing from nuget, but it didn't work:
> dotnet add package Microsoft.Web.WebView2 --version 1.0.774.44

no worries.. i got it.. 
i've installed the runtime and it works now:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

**Comment by philippjbauer** [comment]
Marking this issue closed.
