### ISSUE TITLE
Invalid HTTPS certificat

### ISSUE THREAD

**Issue by alagrede** [tryphotino/tryphotino.github.io#9]
Hello,
I would like to warn you that the website's HTTPS certificate is invalid. https://tryphotino.kavadocs.com/
Cheers

**Comment by MikeYeager** [comment]
Thank you. Which address are you using to access the site? (There are several ways to get there) We'll have someone look into it.

Cheers!
Mike

From: alagrede ***@***.***>
Sent: Wednesday, May 19, 2021 5:34 AM
To: tryphotino/tryphotino.github.io ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tryphotino/tryphotino.github.io] Invalid HTTPS certificat (#9)


Hello,
I would like to warn you that the website's HTTPS certificate is invalid.
Cheers

-

**Comment by alagrede** [comment]
Hello Mike,
Sorry, I updated my comment to include the URL after posting.
The relevant url is: https://tryphotino.kavadocs.com/
Homepage > Documentation

**Comment by MikeYeager** [comment]
Fixed! (finally!)
